### ISSUE TITLE
Not working in Silverstripe 3.2

### ISSUE THREAD

**Issue by EurSylvain** [silverstripe-labs/silverstripe-messagequeue#10]
This module is not working with Silverstripe 3.2 and module Newsletter.

MessageQueue tries to call cli-script or sake. The result is the 404 error page from my website, it nevers call the MessageQueue_Process class.

Could you help me with this issue?

Best regards

**Comment by dhensby** [comment]
Hi @EurSylvain - the issue tracking on GitHub is used for bug reporting where the bug can be described (with steps to replicate) and replicated by others. If you require support then the best place to go is [the forums](http://www.silverstripe.org/community/forums) or our other community resources (http://www.silverstripe.org/community/#introduction)

**Comment by DarrenInwood** [comment]
Added a fix for this at https://github.com/silverstripe-labs/silverstripe-messagequeue/pull/12
